<?php

namespace ExpenseBundle\Repository;

/**
 * CountryspecificexpensesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CountryspecificexpensesRepository extends \Doctrine\ORM\EntityRepository
{
}
