<?php

namespace ExpenseBundle\Repository;

/**
 * ProvenexpenseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProvenexpenseRepository extends \Doctrine\ORM\EntityRepository
{
  public function findLast($employee, $startdate, $enddate) {
      return $this->createQueryBuilder('p')
                  ->where('p.employee = :employee')->setParameter('employee', $employee)
                  ->andWhere('p.startdate = :startdate')->setParameter('startdate', $startdate)
                  ->andWhere('p.enddate = :enddate')->setParameter('enddate', $enddate)
                  ->getQuery()
                  ->getResult();
  }
}
