<?php

namespace MessageBundle\Repository;

/**
 * MessagesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MessagesRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByEmployeeAndType($employee,$type)
    {
        return $this->getEntityManager()
            ->createQuery(
                "SELECT e FROM MessageBundle:Messages e WHERE (e.employee =  '".$employee."' And  e.type = '".$type."') "
            )
            ->getResult();
    }
}
