<?php

namespace AnnouncementsBundle\Repository;

/**
 * AnnouncementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnnouncementRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAllNotExpired()
    {
        $qb = $this->_em->createQueryBuilder();
        $qb->select('a')
        ->from('AnnouncementsBundle:Announcement', 'a')
        ->where('a.expireAt >= :now')
        ->orderBy('a.expireAt', 'ASC')
        ->setParameters(array('now' => new \DateTime()));

        return $qb->getQuery()->getResult();
    }

    public function getAllExpired()
    {
        $qb = $this->_em->createQueryBuilder();
        $qb->select('a')
          ->from('AnnouncementsBundle:Announcement', 'a')
          ->where('a.expireAt <= :now')
          ->setParameters(array('now' => new \DateTime()));

        return $qb->getQuery()->getResult();
    }
}
