<?php

namespace EmployeeBundle\Repository;

/**
 * EmployeeworkingtimeeditgroupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmployeeworkingtimeeditgroupRepository extends \Doctrine\ORM\EntityRepository
{
    public function findEmployee($id)
    {
        return $this->getEntityManager()
            ->createQuery(
                "SELECT e FROM EmployeeBundle:Employeeworkingtimeeditgroup e WHERE e.employeeId = '".$id."'"
            )
            ->getResult();
    }

    public function findByGroup($id)
    {
        return $this->getEntityManager()
            ->createQuery(
                "SELECT e FROM EmployeeBundle:Employeeworkingtimeeditgroup e WHERE e.groupId = '".$id."'"
            )
            ->getResult();
    }
    
}
