<?php

namespace EmployeeBundle\Repository;

/**
 * EmployeeArchivRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmployeeArchivRepository extends \Doctrine\ORM\EntityRepository
{
}
