<?php

namespace EmployeeBundle\Repository;

/**
 * EmployeeworkingtimegroupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmployeeworkingtimegroupRepository extends \Doctrine\ORM\EntityRepository
{
    
    public function findEmployee($id)
    {
        return $this->getEntityManager()
            ->createQuery(
                "SELECT e FROM EmployeeBundle:Employeeworkingtimegroup e WHERE e.employeeId = '".$id."'"
            )
            ->setMaxResults(1)
            ->getOneOrNullResult();
    }
    public function findByGroup($id)
    {
        return $this->getEntityManager()
            ->createQuery(
                "SELECT e FROM EmployeeBundle:Employeeworkingtimegroup e WHERE e.groupId = '".$id."'"
            )
            ->getResult();
    }
    
}
