<?php

namespace EmployeeBundle\Repository;

/**
 * employeepositionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmployeepositionRepository extends \Doctrine\ORM\EntityRepository
{
}
