<?php

namespace EmployeeBundle\Repository;

/**
 * EmployeeImportRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmployeeImportRepository extends \Doctrine\ORM\EntityRepository
{
}
