<?php

namespace EmployeeBundle\Repository;

/**
 * FilesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FilesRepository extends \Doctrine\ORM\EntityRepository
{
  public function findAllFiles()
  {
      return $this->getEntityManager()
          ->createQuery(
              "SELECT e FROM EmployeeBundle:Files e WHERE e.deletedAt IS NULL"
          )
          ->getResult();
  }
}
