<?php

namespace EmployeeBundle\Repository;


/**
 * salaryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SalaryRepository extends \Doctrine\ORM\EntityRepository
{   
    public function findByEmployeeId($employeeId)
    {
        return $this->createQueryBuilder('l')
            ->andWhere('l.employeeId = ?1 And l.deletedAt IS NULL')->setParameter(1, $employeeId)
            ->getQuery()
            ->getResult();
    }
    public function findNewSalary()
    {
        $conn = $this->getEntityManager()->getConnection();
        $sql =  '
        select * , salary.from_date  from employee left join
        (select salary.id , salary.employee_id , salary.comment ,  salary.from_date , salary.to_date  , salary.deleted_at ,salary.salary , salary.create_at from salary where salary.deleted_at IS null GROUP BY employee_id ORDER By from_date  )As salary on salary.employee_id=employee.id where  employee.deleted_at > NOW() AND salary.id IS NOT NULL AND salary.deleted_at IS NULL AND ( salary.from_date < NOW() AND (salary.to_date is NULL OR salary.to_date > NOW()) ) GROUP BY employee.id 
        '        ;
        $stmt = $conn->prepare($sql);
        $stmt->execute();
        return $stmt->fetchAll();
    }
    public function findByEmployeeIdNewSalary($employeeId)
    {
        return $this->createQueryBuilder('l')
            ->andWhere('l.employeeId = ?1 And l.deletedAt IS NULL')->setParameter(1, $employeeId)
            ->orderBy('l.fromDate', 'DESC')
            ->setMaxResults(1)
            ->getQuery()
            ->getResult();
    }
}
