<?php

namespace EmployeeBundle\Repository;

/**
 * WorkingtimeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WorkingtimeRepository extends \Doctrine\ORM\EntityRepository
{
    
}
