<?php

namespace EmployeeBundle\Repository;

/**
 * WorkingHoursPauseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WorkingHoursPauseRepository extends \Doctrine\ORM\EntityRepository
{
}
