# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    encoders:
        FOS\UserBundle\Model\UserInterface:        bcrypt
        Symfony\Component\Security\Core\User\User: plaintext

    # providers:
    #     fos_userbundle:
    #         id:                                  fos_user.user_provider.username_email
    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        in_memory:
            memory:
                users:
                    %trimble_user%:
                        password:                  %trimble_password%
                        roles:                     'ROLE_HTTP'
        fos_userbundle:
            id:                                    fos_user.user_provider.username_email
    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern:                               ^/(_(profiler|wdt)|css|images|js)/
            security:                              false

        trimble:
            pattern:                               ^/trimble
            http_basic:
                realm:                             'Secured Area'
                provider:                          in_memory

        vehicleLogNotloggedout:
            pattern:                               ^/vehicleLogs/notloggedoutmail
            http_basic:
                realm:                             'Secured Area'
                provider:                          in_memory

        absenceNewabsencemail:
            pattern:                               ^/absence/newabsencemail
            http_basic:
                realm:                             'Secured Area'
                provider:                          in_memory

        expensesLoadExpensesByMonth:
            pattern:                               ^/expenses/loadExpensesByMonth
            http_basic:
                realm:                             'Secured Area'
                provider:                          in_memory

        expensesEditedexpensesmail:
            pattern:                               ^/expenses/editedexpensesmail
            http_basic:
                realm:                             'Secured Area'
                provider:                          in_memory

        expensesLoadDayValid:
            pattern:                               ^/expenses/loadDayValid
            http_basic:
                realm:                             'Secured Area'
                provider:                          in_memory

        expensesLoadValiddaysByDay:
            pattern:                               ^/expenses/loadValiddaysByDay
            http_basic:
                realm:                             'Secured Area'
                provider:                          in_memory

        vehicleLoadMonthKm:
            pattern:                               ^/vehicles/loadMonthKm/
            http_basic:
                realm:                             'Secured Area'
                provider:                          in_memory

        main:
            pattern:                               ^/
            form_login:
                provider:                          fos_userbundle
                remember_me:                       true
                csrf_token_generator:              security.csrf.token_manager
                # if you are using Symfony < 2.8, use the following config instead:
                # csrf_provider:                   form.csrf_provider

            logout:
                handlers:                          [app.logoutlistener]
            anonymous:                             true

            remember_me:
                secret:                            "%secret%"
                lifetime:                          31536000
                path:                              /
                domain:                            ~
                user_provider:                     fos_userbundle
                always_remember_me:                true

    access_control:

        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/vehicles/consumptionstatistics, role: [ROLE_USER] }
        - { path: ^/vehicles/consumptionstatistics/[0-9]+, role: [ROLE_USER] }
        - { path: ^/vehicles/allconsumptionstatistics/[0-9]+, role: [ROLE_USER] }
        - { path: ^/vehicles/loadMonthKm/, role: ROLE_HTTP }
        - { path: ^/vehicles, role: [ROLE_ADMIN, ROLE_DISPOSITION] }
        - { path: ^/employee/mycoderandom, role: [ROLE_USER] }
        - { path: ^/employee/mycoderandom, role: [ROLE_USER] }
        - { path: ^/employee/servercodesessionbegin/, role: [ROLE_USER] }
        - { path: ^/employee/editemployeeworkday, role: [ROLE_USER] }
        - { path: ^/employee/CreateDay, role: [ROLE_USER] }
        - { path: ^/employee/deleteWorkingdayByIdJson, role: [ROLE_USER] }
        - { path: ^/employee/createBreaktime, role: [ROLE_USER] }
        - { path: ^/employee/Createbreak, role: [ROLE_USER] }
        - { path: ^/employee/Edit, role: [ROLE_USER] }
        - { path: ^/employee/deleteBreakByIdJson, role: [ROLE_USER] }
        - { path: ^/employee/WorkingtimeEmployeeByMonth/[0-9]+/, role: [ROLE_USER] }
        - { path: ^/employee/createWorkday, role: [ROLE_USER] }
        - { path: ^/employee/indexWorkingdayManagement/, role: [ROLE_ADMIN, ROLE_PERSONAL] }
        - { path: ^/employee/EditBeginStatus/[0-9]+/[0-9]+, role: [ROLE_USER] }
        - { path: ^/employee/EditEndStatus/[0-9]+/[0-9]+, role: [ROLE_USER] }
        - { path: ^/employee/managers, role: [ROLE_USER] }
        - { path: ^/employee/remainingmtl, role: [ROLE_USER] }
        - { path: ^/employee/json, role: [ROLE_ADMIN, ROLE_PERSONAL, ROLE_HOLIDAY] }
        - { path: ^/employee/daysofvacation/update, role: [ROLE_ADMIN, ROLE_PERSONAL, ROLE_HOLIDAY] }
        - { path: ^/contract, role: [ROLE_ADMIN, ROLE_PERSONAL] }
        - { path: ^/employee, role: [ROLE_ADMIN, ROLE_PERSONAL] }
        - { path: ^/expenses/loadExpensesByMonth, role: ROLE_HTTP }
        - { path: ^/expenses/editedexpensesmail, role: ROLE_HTTP }
        - { path: ^/expenses/loadDayValid, role: ROLE_HTTP }
        - { path: ^/expenses/loadValiddaysByDay, role: ROLE_HTTP }
        - { path: ^/expenses/employee, role: [ROLE_USER] }
        - { path: ^/expenses/loadWorkdaysByMonthGet, role: [ROLE_USER] }
        - { path: ^/expenses/expensenew/loadWorkdaysByMonthGetNew, role: [ROLE_USER] }
        - { path: ^/expenses/expensenew/employee, role: [ROLE_USER] }
        - { path: ^/expenses/workday/new, role: [ROLE_USER] }
        - { path: ^/expenses, role: [ROLE_ADMIN, ROLE_PERSONAL] }
        - { path: ^/register, role: ROLE_ADMIN }
        - { path: ^/trimble, role: ROLE_HTTP }
        - { path: ^/message/new, role: [ROLE_ADMIN, ROLE_PERSONAL, ROLE_HOLIDAY] }
        - { path: ^/message, role: [ROLE_USER]}
        - { path: ^/vehicleLogs/blockEmployee, role: [ROLE_ADMIN, ROLE_PERSONAL] }
        - { path: ^/vehicleLogs/setBlockEmployee, role: [ROLE_ADMIN, ROLE_PERSONAL] }
        - { path: ^/vehicleLogs/unBlockEmployee, role: [ROLE_ADMIN, ROLE_PERSONAL] }
        - { path: ^/vehicleLogs/notloggedoutmail, role: ROLE_HTTP }
        - { path: ^/vehicleLogs/loadReservationsByMonth, role: [ROLE_ADMIN, ROLE_DISPOSITION, ROLE_ACCOUNTING] }
        - { path: ^/vehicleLogs/reservation, role: [ROLE_ADMIN, ROLE_DISPOSITION, ROLE_ACCOUNTING] }
        - { path: ^/vehicleLogs/edit, role: [ROLE_ADMIN, ROLE_DISPOSITION, ROLE_ACCOUNTING] }
        - { path: ^/vehicleLogs/show, role: [ROLE_ADMIN, ROLE_DISPOSITION, ROLE_ACCOUNTING] }
        - { path: ^/vehicleLogs, role: ROLE_USER }
        - { path: ^/absence/newabsencemail, role: ROLE_HTTP }
        - { path: ^/absence, role: ROLE_USER }
        - { path: ^/announcement/[0-9]+/edit, role: [ROLE_ADMIN, ROLE_PERSONAL, ROLE_HOLIDAY] }
        - { path: ^/announcement/new, role: [ROLE_ADMIN, ROLE_PERSONAL, ROLE_HOLIDAY] }
        - { path: ^/, role: ROLE_USER }

    role_hierarchy:
        ROLE_SUPER_ADMIN:                          ROLE_ADMIN
        ROLE_ADMIN:                                [ROLE_REDAKTEUR,ROLE_USER]
        ROLE_REDAKTEUR:                            [ROLE_USER]
        ROLE_FUEL_MODUL:                           [ROLE_USER]
        ROLE_CEO:                                  [ROLE_USER]
        ROLE_PERSONAL:                             [ROLE_USER]
        ROLE_HOLIDAY:                              [ROLE_USER]
        ROLE_DISPOSITION:                          [ROLE_USER]
        ROLE_INVOICE:                              [ROLE_USER]
        ROLE_ACCOUNTING:                           [ROLE_USER]
        ROLE_GARAGE:                               [ROLE_USER]
        ROLE_BKF:                                  [ROLE_USER]
        ROLE_ROBOT:                                [ROLE_USER]
        ROLE_AZUBI_PERSONAL:                       [ROLE_USER]
        ROLE_DIALOG_PERSONAL:                      [ROLE_USER]
        # - { path: ^/register, role:                IS_AUTHENTICATED_ANONYMOUSLY }
        # - { path: ^/resetting, role:               IS_AUTHENTICATED_ANONYMOUSLY }
        # - { path: ^/admin/, role:                  ROLE_ADMIN }
        # main:
        #     anonymous:                           ~
            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic:                           ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            #form_login:                           ~
