ExpenseBundle\Entity\Workday:
    type: entity
    table: null
    repositoryClass: ExpenseBundle\Repository\WorkdayRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        date:
            type: date
        workdayBeginTime:
            type: datetime
        workdayEndTime:
            type: datetime
        workdayBeginLat:
            type: decimal
            precision: '8'
            scale: '5'
        workdayBeginLon:
            type: decimal
            precision: '8'
            scale: '5'
        workdayEndLat:
            type: decimal
            precision: '8'
            scale: '5'
        workdayEndLon:
            type: decimal
            precision: '8'
            scale: '5'
        workdayBeginHome:
            type: boolean
            nullable: true
        workdayEndHome:
            type: boolean
            nullable: true
        accommodation:
            type: boolean
            nullable: true
        comment:
            type: string
            length: 255
    lifecycleCallbacks: {  }
    manyToOne:
        truck:
            targetEntity: VehicleBundle\Entity\Vehicle
            inversedBy: truckWorkdays
            joinColumn:
                name: truck_id
                referencedColumnName: id
        country:
            targetEntity: ExpenseBundle\Entity\Countryspecificexpenses
            joinColumn:
                name: country_id
                referencedColumnName: id
        car:
            targetEntity: VehicleBundle\Entity\Vehicle
            inversedBy: carWorkdays
            joinColumn:
                name: car_id
                referencedColumnName: id
        employee:
            targetEntity: EmployeeBundle\Entity\Employee
            inversedBy: workdays
            joinColumn:
                name: employee_id
                referencedColumnName: id
        status:
            targetEntity: AbsenceBundle\Entity\Status
            joinColumn:
                name: status_id
                referencedColumnName: id
