EmployeeBundle\Entity\Department:
    type: entity
    table: null
    repositoryClass: EmployeeBundle\Repository\DepartmentRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
    lifecycleCallbacks: {  }
