<?php

namespace VehicleLogBundle\Repository;

/**
 * VehicleLogPositionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VehicleLogPositionRepository extends \Doctrine\ORM\EntityRepository
{
}
