<?php

namespace VehicleLogBundle\Repository;

/**
 * VehicleReservationPositionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VehicleReservationPositionRepository extends \Doctrine\ORM\EntityRepository
{
}
