<?php

namespace VehicleLogBundle\Repository;

/**
 * VehicleLogReasonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VehicleLogReasonRepository extends \Doctrine\ORM\EntityRepository
{
}
