<?php

namespace VehicleLogBundle\Repository;

/**
 * VehicleReservationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VehicleReservationRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByMonthNoEmployee($begin, $end, $sort = 'vehicleReservationBeginTime', $direction = 'asc') {
        return $this->createQueryBuilder('vr')
                ->andWhere("vr.deletedAt IS NULL AND vr.vehicleReservationBeginTime >= '".$begin."' AND vr.vehicleReservationBeginTime < '".$end."'")
                ->orderBy("vr.".$sort, $direction)
                ->getQuery()
                ->getResult();
    }
}
