<?php

namespace LocationBundle\Repository;

/**
 * LocationtypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LocationtypeRepository extends \Doctrine\ORM\EntityRepository
{
}
