<?php

namespace VehicleBundle\Repository;

/**
 * ConsumptionDetailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConsumptionDetailRepository extends \Doctrine\ORM\EntityRepository
{
}
