<?php

namespace VehicleBundle\Repository;

/**
 * TourRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TourRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByDateVehicle($begin, $end, $vehicle=null) {
        $ret = $this->createQueryBuilder('t')
                ->join('t.originalDetail','o')
                ->leftJoin('t.currentDetail', 'c')
                ->andWhere("(((o.beginn >= :begin AND o.beginn < :end) OR (o.ende >= :begin AND o.ende < :end)) AND o.deleted_at IS NULL) OR (((c.beginn >= :begin AND c.beginn < :end) OR (c.ende >= :begin AND c.ende < :end)) AND c.deleted_at IS NULL)")
                ->setParameter('begin', $begin)
                ->setParameter('end', $end);

        if(!empty($vehicle)) {
            $ret->andWhere("t.vehicle = :vehicle")->setParameter('vehicle', $vehicle);
        }
        
        return $ret->getQuery()
                ->getResult();
    }
    
}
