<?php

namespace VehicleBundle\Repository;

/**
 * TourdetailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TourdetailRepository extends \Doctrine\ORM\EntityRepository
{
}
