<?php

namespace VehicleBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * VehicletypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VehicletypeRepository extends EntityRepository
{
}
