<?php

namespace VehicleBundle\Repository;

/**
 * VehicletypetypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VehicletypetypeRepository extends \Doctrine\ORM\EntityRepository
{
}
