contract_index:
    path:     /
    defaults: { _controller: "EmployeeBundle:Contract:index" }
    methods:  GET

contract_show:
    path:     /{id}/show
    defaults: { _controller: "EmployeeBundle:Contract:show" }
    methods:  GET

contract_new:
    path:     /new
    defaults: { _controller: "EmployeeBundle:Contract:new" }
    methods:  [GET, POST]

contract_edit:
    path:     /{id}/edit
    defaults: { _controller: "EmployeeBundle:Contract:edit" }
    methods:  [GET, POST]

contract_delete:
    path:     /{id}/delete
    defaults: { _controller: "EmployeeBundle:Contract:delete" }
    methods:  DELETE
