<?php

namespace TrimbleSoapBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TracedatapropertyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TracedatapropertyRepository extends EntityRepository
{
}
