<?php

namespace TrimbleSoapBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TracepolldataRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TracepolldataRepository extends EntityRepository
{
}
