<?php

namespace TrimbleSoapBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TracetypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TracetypeRepository extends EntityRepository
{
}
