<?php

namespace AbsenceBundle\Repository;

/**
 * AbsenceClearingRecordsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AbsenceClearingRecordsRepository extends \Doctrine\ORM\EntityRepository
{
}
