<?php

namespace AbsenceBundle\Repository;

/**
 * HolidayscheduleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HolidayscheduleRepository extends \Doctrine\ORM\EntityRepository
{

  public function getHolidayscheduleByEmployeeAndYear($employee, $year)
  {
      $qb = $this->_em->createQueryBuilder();
      $qb->select('h')
          ->from('AbsenceBundle:Holidayschedule', 'h')
          ->Where('h.employee = :employee')
          ->andWhere('h.year = :year')
          ->setMaxResults(1)
          ->setParameters(array('employee' => $employee, 'year' => $year));
      return $qb->getQuery()->getOneOrNullResult();
  }


}
