<?php

namespace AbsenceBundle\Repository;

/**
 * ReasonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReasonRepository extends \Doctrine\ORM\EntityRepository
{
}
