<?php

namespace AbsenceBundle\Repository;

/**
 * VacationlockRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VacationlockRepository extends \Doctrine\ORM\EntityRepository
{
}
