---
engines:
  duplication:
    enabled: true
    config:
      languages:
        - javascript
  eslint:
    enabled: true
    channel: 'eslint-3'
  fixme:
    enabled: true
ratings:
  paths:
    - 'src/**/*.js'
exclude_paths:
  - 'dist/'
  - 'docs/'
  - '**.json'
  - '**.md'
  - '**.sh'
  - 'gulpfile.js'
  - 'rollup.config.js'
