ExpenseFinanzamtEmployee:
    path:     /{employee_id}/{year}
    defaults: { _controller: "ExpenseBundle:ExpenseFinanzamt:index" }
    methods:  GET   
    requirements:
        employee_id: '\d+'
        year: '\d{4}'  
ExpenseFinanzamtEmployeeSave:
    path:     /save/{employee_id}/{date}/{expense1}/{expense2}/{expense3}
    defaults: { _controller: "ExpenseBundle:ExpenseFinanzamt:expensesSave" }
    methods:  GET   
    requirements:
        employee_id: '\d+'
        expense1: '\d+'
        expense2: '\d+'
        expense3: '\d+'
        date: '\d{4}-\d{2}-\d{2}'
ExpenseFinanzamtprint:
    path:     /print/{employee_id}/{date}
    defaults: { _controller: ExpenseBundle:ExpenseFinanzamt:print }
    requirements:
        employee_id: '\d+'           
        date: '\d\d\d\d'
ExpenseFinanzamtDelete:
    path:     /del/{id}
    defaults: { _controller: ExpenseBundle:ExpenseFinanzamt:expensesDelete }
    requirements:
        id: '\d+'           
ExpenseFinanzamtprintmonth:
    path:     /print/{employee_id}/{date}
    defaults: { _controller: ExpenseBundle:ExpenseFinanzamt:printMonth }
    requirements:
        employee_id: '\d+'           
        date: '\d{4}-\d{2}-\d{2}'     